### ISSUE TITLE
Taking in account your hiera ? 

### ISSUE THREAD

**Issue by rgarrigue** [inkblot/puppet-bind#117]
Hello

What's the trick to take into account your hiera.yaml, plus data/ stuff ? I had to drop a c/c of RedHat.yml in my nodes/{{fqdn}}.yml, otherwise I'm screwed.

```
bind::defaults::supported: true
bind::defaults::bind_user: 'named'
...
```

Regards,

**Comment by inkblot** [comment]
Earlier versions of the module relied on `ripienaar/module_data` and worked with Puppet 3.x. Since version 6.0, after implementation of the current arrangement, the module requires the module data support that is now built into Puppet 4.x. It's documented [here](https://docs.puppet.com/puppet/4.9/hiera_layers.html).
