### ISSUE TITLE
Must pass bind_service to Class[Bind::Params] at .../modules/bind/manifests/init.pp:13

### ISSUE THREAD

**Issue by aimonb** [inkblot/puppet-bind#48]
Hi, the params class is included with no args. But the params class has no defaults for its args. How does this work?

**Comment by aimonb** [comment]
OK I see that the module_data module should have picked that info up. It is not in my case.. why? I am by the way using hiera extensively already. Am I overriding the load order?

**Comment by aimonb** [comment]
aha! So if anyone else has this issue. You need to add the backend to your /etc/puppet/hiera.yaml:

:backends:
  - module_data

**Comment by fonk** [comment]
+1 for updating the docs!

**Comment by inkblot** [comment]
I have not needed to do this. Is this related to the puppet version?

**Comment by nerdlich** [comment]
For me, it doesn't even work when adding module_data to the backends (yes, module_data module is installed).

**Comment by inkblot** [comment]
What version of puppet are you using?

**Comment by nerdlich** [comment]
3.8.2

**Comment by inkblot** [comment]
Ok. I've got 3.8.1 on my master, and a mix of 3.8.1 and 3.4.3 on agents and standalone systems. I've also noticed that I've got no version requirement in the bind module's dependency on module_data, but due to the constraints in other modules in my config repo, I'm getting module_data 0.0.3, which includes some auto-registration code that needed work between 0.0.2 and 0.0.3 in order to work with later puppets. I've pushed a branch that just adds a module_data version constraint. Can you try it and see? It's the `module-data-version` branch.

**Comment by nerdlich** [comment]
I had already installed module_data v0.0.4. No worries. There might be something else wrong with my setup.
