### ISSUE TITLE
using bind::updater on bind server

### ISSUE THREAD

**Issue by zipkid** [inkblot/puppet-bind#77]
When applying bind::updater on all nodes this causes conflicts on the bind server.

**Comment by inkblot** [comment]
`bind` and `bind::updater` are intended to be mutually exclusive.

**Comment by zipkid** [comment]
Why intentionally create conflict?

**Comment by inkblot** [comment]
Ok, so I'm looking at #78 and thinking to myself "Does this actually fix it?" because years ago I tried to and it was a complete mess. Then I realized, `bind::defaults` which both `bind` and `bind::updater` inherit no longer has resources in it, and `bind::keydir` is a lot simpler than it used to be. It was less about intent and more about the big hurdles that stood in the way.

Let's move the discussion to #78
